"""Added created_at to diagnosis model

Revision ID: 35db8da57f74
Revises: 902f6495ac1a
Create Date: 2025-06-05 17:27:54.407400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35db8da57f74'
down_revision: Union[str, None] = '902f6495ac1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis', 'created_at')
    # ### end Alembic commands ###
