"""Added dob to User

Revision ID: 902f6495ac1a
Revises: 
Create Date: 2025-06-05 16:40:46.059569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '902f6495ac1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    op.create_table('heart_rate',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('heart_rate_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('goal',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('target_date', sa.DATE(), nullable=False),
    sa.Column('is_complete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('goal_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('goal_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
