"""Updated Diagnosis table to have doctor_id

Revision ID: c9c532a2d2df
Revises: 005b56ba8afe
Create Date: 2025-06-05 19:21:33.651449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c532a2d2df'
down_revision: Union[str, None] = '005b56ba8afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnosis', type_='foreignkey')
    op.drop_column('diagnosis', 'doctor_id')
    # ### end Alembic commands ###
